# Generated by Django 6.0.3 on 2026-03-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtodo',
            old_name='task',
            new_name='description',
        ),
    ]
