# Generated by Django 6.0.3 on 2026-04-03 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_task_addtodo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtodo',
            old_name='iscomplete',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='addtodo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='addtodo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addtodo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='addtodo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
